services:
  db-market:
    container_name: db-market
    image: postgres:17.5
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./migration/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  store-market-cache:
    container_name: redis-cache
    image: redis:7.4.2-bookworm
    ports:
      - '6379:6379'
    networks:
      - market-network

  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KC_DB: dev-mem
      KC_LOG_LEVEL: INFO
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-master.json:/opt/keycloak/data/import/realm-master.json:ro
    command:
      - start-dev
      - --import-realm
    ports:
      - '8082:8080'
    networks:
      - market-network

  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - OAUTH2_HOST=http://keycloak-service:8080
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    networks:
      - market-network

  market-service:
    container_name: market-service
    build:
      context: ./my-market-service/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db-market
      - POSTGRES_PORT=5432
      - PAYMENT_SERVICE_PORT=8081
      - PAYMENT_SERVICE_HOST=payment-service
      - OAUTH2_HOST=http://keycloak-service:8080
      - REDIS_HOST=store-market-cache
      - REDIS_PORT=6379
      - SPRING_DATA_REDIS_HOST=store-market-cache
      - SPRING_DATA_REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - db-market
      - store-market-cache
      - keycloak
      - payment-service
    networks:
      - market-network
    restart: on-failure

networks:
  market-network:
    driver: bridge
    name: market-network

volumes:
  postgres_data:
    name: postgres_market_data