server:
  port: 8080

spring:
  webflux:
    session:
      timeout: 30m
  r2dbc:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}