server:
  port: 8081

service:
  default-balance: ${DEFAULT_BALANCE:5000}

spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_HOST:http://localhost:8082}${OAUTH2_SERVER_URL:/realms/master}